#!/bin/sh
eval $(minikube docker-env)

version=$(cat version)
version=$((version+1))

echo $version > version

docker build -t hello-node:v$version .

# kubectl set image deployment/hello-node hello-node=hello-node:v$version

